# Generated by Django 5.1.2 on 2024-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code', verbose_name='User QR'),
        ),
    ]
