# Generated by Django 5.1.2 on 2024-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
