# Generated by Django 5.1.2 on 2024-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_myuser_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='verify_code',
            field=models.IntegerField(blank=True, default=0, verbose_name='verify code'),
            preserve_default=False,
        ),
    ]
