# Generated by Django 5.1.2 on 2024-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_myuser_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='is_verify'),
        ),
    ]
