# Generated by Django 5.1.2 on 2024-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_myuser_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('session_timeout', models.IntegerField(default=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
