# Generated by Django 5.1.2 on 2024-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='img',
            field=models.ImageField(default='m7XuV1i6egth4ISiD240.jpg', null=True, upload_to='user_images', verbose_name='User Image'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
    ]
